### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by ToluClassics** [theyorubayesian/rapala#4]
Hi @Seun-Ajayi x @theyorubayesian  ,

I have some questions and some updates; 

why are we hard coding the pages here? is it possible to get all the pages for a particular language?
``` self.sources = [
            "https://www.voaswahili.com/z/4658/?p={}",
            "https://www.voaswahili.com/z/4657/?p={}",
            "https://www.voaswahili.com/z/4660/?p={}",
            "https://www.voaswahili.com/z/4768/?p={}",
            "https://www.voaswahili.com/z/4659/?p={}",
            "https://www.voaswahili.com/z/2774/?p={}",
            "https://www.voaswahili.com/z/2775/?p={}",
            "https://www.voaswahili.com/z/2783/?p={}",
        ]
```

@Seun-Ajayi , can you extend the class to use firefox driver too? so maybe the user can select the browser they want?

@Seun-Ajayi , can we take out some of the inline comments and just leave the class comments?

**Comment by theyorubayesian** [comment]
@Seun-Ajayi  please checkout a new branch before attending to these.
