### ISSUE TITLE
Random 

### ISSUE THREAD

**Issue by ToluClassics** [theyorubayesian/rapala#6]
@Seun-Ajayi in other non project related issues, how interested are you in NLP?

**Comment by Seun-Ajayi** [comment]
I've not really explored NLP outside what I was introduced to in AISaturdays Lagos; label-studio...
But, yes I'm interested and curious. I like project-based learning.

**Comment by ToluClassics** [comment]
Sounds good then; what's your experience with pytorch like?

I'm looking to create a set of tutorials similar to this https://github.com/NielsRogge/Transformers-Tutorials; but it will be a primer on getting started on NLP in low resource languages

**Comment by Seun-Ajayi** [comment]
TBH, I have zero experience with pytorch but I'm positive that with proper guidelines on what's needed to be learnt to get the job done, I can make sense of this. Come to think that the first time I heard of seleniun was when Tunde mentioned this project. 

So, where do we start from?

**Comment by ToluClassics** [comment]
You can start here: https://pytorch.org/tutorials/  or here: https://www.youtube.com/watch?v=GIsg-ZUy0MY&t=33798s
while I work on some form of curriculum to help us along the way; 

I can help if you need anything along the way with learning pytorch.

**Comment by Seun-Ajayi** [comment]
Well, I visited the first link before replying your initial message but I just brushed through to check what pytorch looks like, so I would get back there now and do the real deal and I would let you now when I need help, Thank YOU.

**Comment by ToluClassics** [comment]
Sounds like a plan

**Comment by ToluClassics** [comment]
@Seun-Ajayi How's it going bro

**Comment by Seun-Ajayi** [comment]
I chose the YouTube video instead and though I had issues downloading pytorch and its neighbors but it's all good now and it's making sense, I'm some few hours away from completing the tutorial. Never knew I would be learning PyTorch all of a sudden.

**Comment by Seun-Ajayi** [comment]
@ToluClassics, I have eventually completed the PyTorch tutorial, I now have a fair idea of PyTorch and Deep Learning, I'm positive that with more practice I would get more familiar with it. The tutorial covered from the basics to GANs and I found it interesting and well explained. 

Is there exercises you would like to give or **what's next**?

**Comment by ToluClassics** [comment]
Sounds good! LGTM 🚀
Adding you to a repo now

I've created the first issue to work on

**Comment by Seun-Ajayi** [comment]
Alright boss

**Comment by Seun-Ajayi** [comment]
Well, I visited the first link before replying your initial message but I
just brushed through to check what pytorch looks like, so I would get back
there now and do the real deal and I would let you now when I need help,
Thank YOU.
